const mongoose = require("mongoose");

// Reusable validation function for URL format
function validateURL(url: string) {
  return /^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/.test(url);
}

// Document schema
const schema = new mongoose.Schema(
  {
    // _id will be auto-generated by Mongo
    name: { type: String, required: true },
    url: {
      type: String,
      unique: true,
      trim: true,
      required: true,
      validate: [validateURL],
    },
    contactDetails: {
      type: String,
      validate: {
        validator: function (v: string) {
          // Regular expression pattern for phone number validation
          return /^(\+\d{1,2}\s?)?1?-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/.test(
            v
          );
        },
        message: (props: any) => `${props.value} is not a valid phone number!`,
      },
      required: false,
    },
    socialMediaUrls: [
      {
        // id: { type: String, required: true },
        name: { type: String, required: true },
        socialMedia_url: {
          type: String,
          trim: true,
          unique: true,
          validate: {
            validator: validateURL,
            message: (props: any) => `${props.value} is not a valid URL!`,
          },
          required: false,
        },
        icon: { type: String, required: true },
      },
    ],
    streamingUrls: [
      {
        // id: { type: String, required: true },
        name: { type: String, required: true },
        streaming_url: {
          type: String,
          trim: true,
          unique: true,
          validate: {
            validator: validateURL,
            message: (props: any) => `${props.value} is not a valid URL!`,
          },
          required: false,
        },
        icon: { type: String, required: true },
      },
    ],

    bannerImg: {
      type: String,
      validate: {
        validator: validateURL,
        message: (props: any) => `${props.value} is not a valid URL!`,
      },
      required: false,
    },

    coverImg: {
      type: String,
      validate: {
        validator: validateURL,
        message: (props: any) => `${props.value} is not a valid URL!`,
      },
      required: false,
    },

    aboutImg: {
      type: String,
      validate: {
        validator: validateURL,
        message: (props: any) => `${props.value} is not a valid URL!`,
      },
      required: false,
    },

    aboutUs: { type: String, required: false },
    headline: { type: String, required: false },
    tagline: { type: String, required: false },

    mediaUrls: [
      {
        // id: { type: String, required: true },
        type: { type: String, required: true },
        media_url: {
          type: String,
          trim: true,
          unique: true,
          validate: {
            validator: validateURL,
            message: (props: any) => `${props.value} is not a valid URL!`,
          },
          required: false,
        },
      },
    ],
    isActive: { type: Boolean, default: true },
  },
  {
    timestamps: true,
  }
);

const DomainModel = mongoose.model("domainNew", schema);

export default DomainModel;
