const mongoose = require('mongoose');

// Reusable validation function for URL format
function validateURL(url) {
  return /^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/.test(url);
}

// Document schema
const schema = new mongoose.Schema(
  {
    // _id will be auto-generated by Mongo
    name: { type: String, required: true },
    url: { type: String, trim: true, required: true, validate: [validateURL] },
    contactDetails: {
      type: String,
      validate: {
        validator: function (v) {
          // Regular expression pattern for phone number validation
          return /^(\+\d{1,2}\s?)?1?-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/
          .test(
            v,
          );
        },
        message: (props) => `${props.value} is not a valid phone number!`,
      },
      required: true,
    },
    socialMediaUrls: [{
      // id: { type: String, required: true },
      name: { type: String, required: true },
      social_url: {
        type: String,
        trim: true,
        validate: {
          validator: validateURL,
          message: (props) => `${props.value} is not a valid URL!`,
        },
        required: true,
      },
      icon: { type: String, required: true },
    }],
    streamingUrls: [{
      // id: { type: String, required: true },
      name: { type: String, required: true },
      stream_url: {
        type: String,
        trim: true,
        validate: {
          validator: validateURL,
          message: (props) => `${props.value} is not a valid URL!`,
        },
        required: true,
      },
      icon: { type: String, required: true },
    }],
    isActive: { type: Boolean, default: true },
  },
  {
    timestamps: true,
  },
);

// const DomainModel = mongoose.model('Domain', schema);
const DomainModel = mongoose.model('domainNew', schema);

module.exports = DomainModel;
